server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:9090/eureka/
error:
  whitelabel:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'